// Mock job data
export const jobs = [
    {
      id: "1",
      title: "UX Designer",
      company: "Google",
      location: "Hybrid",
      type: "Full-time",
      salary: "RM65k - RM85k / annum",
      postedDate: "2025-10-10",
      matchScore: 90,
      accommodationsFriendly: true,
      description:
        "Join Google's design team to create accessible and inclusive user experiences. We value diverse perspectives and neurodivergent thinking.",
      requirements: ["Figma", "User Research", "Prototyping", "Accessibility"],
      benefits: ["Health Insurance", "Flexible Hours", "Hybrid Work", "Professional Development"],
      companySize: "10,000+ employees",
      industry: "Technology / Design",
      applicationDeadline: "2025-11-10",
      neurodivergentFriendly: true,
      logo: "/Google_Logo.png",
    },
    {
      id: "2",
      title: "Consultant",
      company: "PwC",
      location: "Remote",
      type: "Full-time",
      salary: "RM80k - RM110k / annum",
      postedDate: "2025-10-08",
      matchScore: 88,
      accommodationsFriendly: true,
      description:
        "Consult on neurodivergent inclusion and workplace adaptation strategies. Collaborate with organizations to foster inclusive environments.",
      requirements: ["Consulting", "Communication", "Change Management", "Diversity & Inclusion"],
      benefits: ["Remote Work", "Flexible Hours", "Professional Development", "Inclusive Environment"],
      companySize: "10,000+ employees",
      industry: "Consulting / HR",
      applicationDeadline: "2025-11-08",
      neurodivergentFriendly: true,
      logo: "/PwC_Logo.png",
    },
    {
      id: "3",
      title: "Developer",
      company: "Gamuda",
      location: "Remote",
      type: "Full-time",
      salary: "RM70k - RM90k / annum",
      postedDate: "2025-10-09",
      matchScore: 87,
      accommodationsFriendly: true,
      description:
        "Develop innovative software for sustainable infrastructure projects in an inclusive environment.",
      requirements: ["JavaScript", "React", "Node.js", "Tailwind CSS"],
      benefits: ["Health Insurance", "Remote Work", "Flexible Hours", "Professional Development"],
      companySize: "1,000+ employees",
      industry: "Engineering / Technology",
      applicationDeadline: "2025-11-09",
      neurodivergentFriendly: true,
      logo: "/Gamuda_Logo.png",
    },
    {
      id: "4",
      title: "Data Analyst",
      company: "SLB",
      location: "Part-time",
      type: "Part-time",
      salary: "RM40k - RM55k / annum",
      postedDate: "2025-10-06",
      matchScore: 84,
      accommodationsFriendly: true,
      description:
        "Analyze datasets to improve energy efficiency and inclusivity. Ideal for those passionate about sustainability and data-driven impact.",
      requirements: ["Python", "SQL", "Excel", "Data Visualization"],
      benefits: ["Flexible Hours", "Professional Development", "Hybrid Work"],
      companySize: "10,000+ employees",
      industry: "Energy / Data Analytics",
      applicationDeadline: "2025-11-06",
      neurodivergentFriendly: true,
      logo: "/SLB_Logo.png",
    },
    {
      id: "5",
      title: "Frontend Developer",
      company: "NeuroTech",
      location: "Remote",
      type: "Full-time",
      salary: "RM70k - RM90k / annum",
      postedDate: "2025-10-09",
      matchScore: 91,
      accommodationsFriendly: true,
      description:
        "We are looking for a frontend developer with strong React and Tailwind skills to join our inclusive team focused on neurodivergent-friendly technology.",
      requirements: ["React", "Tailwind CSS", "JavaScript", "REST APIs"],
      benefits: ["Health Insurance", "Remote Work", "Flexible Hours", "Inclusive Culture"],
      companySize: "50-100 employees",
      industry: "Technology / Accessibility",
      applicationDeadline: "2025-11-09",
      neurodivergentFriendly: true,
    },
    {
      id: "6",
      title: "Data Analyst",
      company: "InclusionWorks",
      location: "Singapore",
      type: "Part-time",
      salary: "RM40k - RM55k / annum",
      postedDate: "2025-10-06",
      matchScore: 83,
      accommodationsFriendly: false,
      description:
        "Analyze workforce data and help companies make inclusive, data-driven decisions to enhance diversity in the workplace.",
      requirements: ["Python", "Excel", "Statistics", "Reporting"],
      benefits: ["Flexible Hours", "Professional Development", "Collaborative Team"],
      companySize: "100-500 employees",
      industry: "Analytics / Inclusion Consulting",
      applicationDeadline: "2025-11-06",
      neurodivergentFriendly: true,
    },
    {
      id: "7",
      title: "UX Designer",
      company: "DesignForward",
      location: "Hybrid",
      type: "Full-time",
      salary: "RM65k - RM85k / annum",
      postedDate: "2025-10-03",
      matchScore: 89,
      accommodationsFriendly: true,
      description:
        "Create inclusive and accessible user experiences for neurodivergent users. Collaborate with cross-functional teams to design human-centered interfaces.",
      requirements: ["Figma", "UX Research", "Wireframing", "Accessibility"],
      benefits: ["Health Insurance", "Flexible Hours", "Professional Development", "Hybrid Work"],
      companySize: "11-50 employees",
      industry: "Design / Accessibility",
      applicationDeadline: "2025-11-03",
      neurodivergentFriendly: true,
    },
    {
      id: "8",
      title: "Software Engineer",
      company: "TechInclusive",
      location: "Remote",
      type: "Full-time",
      salary: "RM80k - RM110k / annum",
      postedDate: "2025-10-08",
      matchScore: 90,
      accommodationsFriendly: true,
      description:
        "Build scalable software solutions in a neurodivergent-friendly environment. Collaborate on projects focused on accessibility and inclusion.",
      requirements: ["Python", "React", "Node.js", "Cloud Services"],
      benefits: ["Health Insurance", "Remote Work", "Flexible Hours", "Inclusive Culture"],
      companySize: "50-100 employees",
      industry: "Technology / Accessibility",
      applicationDeadline: "2025-11-08",
      neurodivergentFriendly: true,
    },
  ];